variables:
  DOCKER_DRIVER: overlay


client-test:
  image: tmaier/docker-compose:latest
  services:
  - docker:dind
  stage: test
  cache:
    paths:
      - node_modules/
  script:
  - docker info
  - docker-compose --version
  - if command -v apk > /dev/null; then apk add --no-cache bash; fi
  # - apk add --no-cache bash
#  - bash ./docker-compose/client/run_client_tests.sh
  - bash ./docker-compose/migrations/run_migration_tests.sh mysql
  # - time npm test
  # - echo "tests ran?"
  when: manual
  # tags:
  #   - shell
  #   - docker
